openapi: 3.0.3
info:
  title: XCD HR Connect APIs
  version: '1.0'
  description: >-
    The XCD HR Connect APIs enable seamless integration with the XCD HR & Payroll
    application deployed on a client's Salesforce organization, facilitating HR
    operations such as leave management, expense creation, and timesheet
    submission. Designed for efficiency, the API supports both synchronous and
    asynchronous calls and is optimized for handling large datasets through bulk
    operations.
paths:
  /xcdio__Leave_API__c:
    post:
      tags:
        - Leave
      summary: Book Leave
      servers:
        - url: https://mydomain.my.salesforce.com/services/apexrest/xcdio/xcdapi/v1.0
      operationId: 'BookLeave'
      requestBody:
        description: Book Leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookLeave'
            examples:
              Annual Leave:
                value:
                  records:
                    - xcdio__Leave_Category__c: "Annual Leave"
                      xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                      xcdio__Start_Date__c: "2025-01-10"
                      xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                      xcdio__End_Date__c: "2025-01-12"
                      xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                    - xcdio__Leave_Category__c: "Annual Leave"
                      xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                      xcdio__Start_Date__c: "2025-02-05"
                      xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                      xcdio__End_Date__c: "2025-02-06"
                      xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                      xcdio__Notes__c: "Holiday"
                  response_fields: "xcdio__Leave_Request__c"
                  asynchronous: "false"
                  allOrNone: "true"
              Sick Leave:
                value:
                  records:
                    - xcdio__Leave_Category__c: "Sick Leave"
                      xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                      xcdio__Start_Date__c: "2025-01-10"
                      xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                      xcdio__End_Date__c: "2025-01-12"
                      xcdio__End_Date_AM_PM_All_Day__c: "All Day"
                      xcdio__Illness__c: "Other"
                    - xcdio__Leave_Category__c: "Sick Leave"
                      xcdio__Employee_Details__c: "a29Q1000000t6zFIAQ"
                      xcdio__Start_Date__c: "2025-02-05"
                      xcdio__Start_Date_AM_PM_All_Day__c: "All Day"
                      xcdio__Expected_return_to_work_date__c: "2025-02-7"
                      xcdio__Illness__c: "Infection"
                  response_fields: "xcdio__Leave_Request__c"
                  asynchronous: "false"
                  allOrNone: "true"
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BookLeaveApiResponseSuccess' 
                  - $ref: '#/components/schemas/BookLeaveAsyncApiResponseSuccess'
              examples:
                synchronous:
                  value:
                    - success: true
                      errors: []
                      xcdio__Leave_Request__c: a10Q100000kS97VIAS
                      Id: a29Q1000000t6zFIAQ
                      record_Sequence: 1
                    - success: false
                      errors: ["Sorry, the new Leave/Absence request could not be created as the dates entered for the new Leave/Absence request coincide/overlap with the dates of an existing Leave/Absence. Please confirm the dates and try again for the Role(s):  Dev"]
                      xcdio__Leave_Request__c: null
                      Id: null
                      record_Sequence: 2
                asynchronous:
                  value:
                    - batch_Id: 1ea4b976fa600903
                      errors: []
                  
                
        '400':
          description: Request Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["System.CalloutException: Invalid API Version"]
                  
        '403':
          description: Insufficient Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["sObject type 'xcdio__Leave_API__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."]
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["NullPointerException: ..."]
        
        default:
          description: Default error sample response
    patch:
      tags:
        - Leave
      summary: Edit & Cancel Leave
      operationId: 'EditLeave'
      requestBody:
        description: Edit & Cancel Leave
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditLeave'
            example:
              records:
                - xcdio__Leave_request__c: "a10Q100000iqtztIAA"
                  xcdio__Approval_Status__c: "Cancelled"
                - xcdio__Leave_request__c: "a10Q100000iqtzsIAA"
                  xcdio__Approval_Status__c: "Recalled"
              asynchronous: "false"
              allOrNone: "true"
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                    - $ref: '#/components/schemas/BookLeaveApiResponseSuccess' 
                    - $ref: '#/components/schemas/BookLeaveAsyncApiResponseSuccess'
              examples:
                synchronous:
                  value:
                    - success: true
                      errors: []
                      xcdio__Leave_Request__c: a10Q100000kS97VIAS
                      Id: a29Q1000000t6zFIAQ
                      record_Sequence: 1
                    - success: true
                      errors: []
                      xcdio__Leave_Request__c: a10S900000Mqng1IAB
                      Id: a28S9000000TCAgIAO
                      record_Sequence: 2
                asynchronous:
                  value:
                    - batch_Id: 1ea4b976fa600903
                      errors: []
        '400':
          description: Request Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["System.CalloutException: Invalid API Version"]
                  
        '403':
          description: Insufficient Permission
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["sObject type 'xcdio__Leave_API__c' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names."]
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookLeaveApiResponseFailure' 
              example:
                - success: false
                  errors: ["NullPointerException: ..."]
        
        default:
          description: Default error sample response
  /graphql:
    post:
      tags:
        - GraphQL API
      summary: Query XCD Object Records
      servers:
        - url: https://mydomain.my.salesforce.com/services/data/v61.0/graphql
      operationId: 'QueryRecords'
      requestBody:
        description: Query Batch Status
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  format: json
                  description: GraphQL query.
                  example:
                     "query GetAsyncDetail($batchId: String!) { uiapi { query { xcdio__Leave_API__c(where: { xcdio__API_System_Attributes__r: { xcdio__Batch_Id__c: { eq: $batchId } } }) { edges { node { Id xcdio__API_System_Attributes__r { xcdio__Status__c { value } xcdio__CRUD_Type__c { value } xcdio__Success__c { value } } xcdio__Leave_Request__r { Id Name { value } xcdhcm__Approval_Status__c { value } } } } } } } }"
                variables:
                  type: string
                  format: json
                  description: GraphQL query variable values, if any. 
                  example:
                    {"batchId": "1ea4b976fa600903"}
              required: 
                - query
            examples:
                Query XCD Employee/Personal/Job role:
                  value:
                      query: "query GetEmployeeDetail($employeeId: ID!) { uiapi { query { xcdhcm__Employee_Detail__c(where: { Id: { eq: $employeeId } }) { edges { node { Name { value } xcdhcm__Employee_Number__c { value } xcdhcm__Work_email__c { value } xcdhcm__Start_Date__c { value } xcdhcm__Leaving_Date__c { value } xcdhcm__Payroll_start_date__c { value } xcdhcm__Personal_L__r { Id xcdhcm__First_name__c { value } xcdhcm__Middle_name__c { value } xcdhcm__Home_phone__c { value } } xcdhcm__Job_Role__r { xcdhcm__Department_L__r { xcdhcm__Departments_code__c { value } } } } } } } }"
                      variables: { "employeeId": "a0WPt0000019TtRMAU" }
                Query XCD API Aysnchronous Batch ID Status:
                  value:
                      query: "query GetAsyncDetail($batchId: String!) { uiapi { query { xcdio__Leave_API__c(where: { xcdio__API_System_Attributes__r: { xcdio__Batch_Id__c: { eq: $batchId } } }) { edges { node { Id xcdio__API_System_Attributes__r { xcdio__Status__c { value } xcdio__CRUD_Type__c { value } xcdio__Success__c { value } } xcdio__Leave_Request__r { Id Name { value } xcdhcm__Approval_Status__c { value } } } } } } } }"
                      variables: { "batchId": "a0WPt0000019TtRMAU" }
              
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    format: json
                    description: GraphQL queried data.
                    example: test
                  errors:
                    type: array
                    items:
                      type: string
                      format: json
                    description: GraphQL query errors, if any. 
                    example:
              examples:
                Query XCD Employee/Personal/Job role response:
                  value:
                      data: {"uiapi":{"query":{"xcdhcm__Employee_Detail__c":{"edges":[{"node":{"Id":"a0WPt0000019TtRMAU","Name":{"value":"Test Employee"},"xcdhcm__Employee_Number__c":{"value":"wjD 4"},"xcdhcm__Work_email__c":{"value":"bsq@peoplexcd.com"},"xcdhcm__Start_Date__c":{"value":"2024-04-01"},"xcdhcm__Leaving_Date__c":{"value":null},"xcdhcm__Payroll_start_date__c":{"value":"2024-04-01"},"xcdhcm__Personal_L__r":{"Id":"a1VPt000001kXq1MAE","xcdhcm__First_name__c":{"value":"Test"},"xcdhcm__Middle_name__c":{"value":null},"xcdhcm__Home_phone__c":{"value":"99999"}},"xcdhcm__Job_Role__r":{"xcdhcm__Department_L__r":{"xcdhcm__Departments_code__c":{"value":"1234"}}}}}]}}}}
                      errors: []
                Query Aysnc Batch ID Response (Success):
                  value:
                      data: {"uiapi":{"query":{"xcdio__Leave_API__c":{"edges":[{"node":{"Id":"a28Pt000000x0LmIAI","xcdio__API_System_Attributes__r":{"xcdio__Status__c":{"value":"Completed"},"xcdio__CRUD_Type__c":{"value":"Create"},"xcdio__Success__c":{"value":true}},"xcdio__Leave_Request__r":{"Id":"a10Pt00000aqPQbIAM","Name":{"value":"LR-0018"},"xcdhcm__Approval_Status__c":{"value":"Approved"}}}}]}}}}
                      errors: []
                        
                Query Aysnc Batch ID Response (Error):
                  value:
                      data: {}
                      errors: [{"message":"Field 'xcdio__Statuss__c' does not exist on type 'xcdio__API_System_Attributes__r'.","locations":[{"line":5,"column":13}],"path":["edges",0,"node","xcdio__API_System_Attributes__r","xcdio__Statuss__c"],"extensions":{"code":"FIELD_NOT_FOUND","details":"The requested field does not exist in the schema."}}]
components:
  schemas:
    BookLeave:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: Array of leave request records to be created, as described in the BookLeaveRecordDetail schema. Every XCD API has a threshold number of records that can be passed in a single synchronous request, defined in the "XCD Integration API" custom metadata. The number of records in an asynchronous request can be up to 10,000.
          items:
            $ref: '#/components/schemas/BookLeaveRecordDetail' 
        response_fields:
          type: string
          description: Comma-separated list of fields in the API object. Any new field can be added to the API object and dynamically queried using this field.
          example: xcdio__Leave_Request__c or xcdio__Leave_Request__c, xcdio__Approval_Status__c
        asynchronous:
          type: string
          description: Request execution context. Synchronous requests will provide a response as part of the same request. Asynchronous requests return a single batch_Id for the entire array, which can be further queried for the request status and other fields. Refer GraphQL API section in this document on how to query request details using batch_id. 
          format: boolean
          default: "false"
        allOrNone:
          type: string
          format: boolean
          default: true
          description: Allow partial leave records to be created if one or more records in the array have validation errors.
          
    BookLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_Category__c:
          type: string
          enum:
            - Annual Leave
            - Sick Leave
          description: The category of leave defined in XCD HRMS.
          example: Annual Leave
        xcdio__Employee_Details__c:
          type: string
          description: Salesforce record ID of the employee for whom the leave is to be booked.
          example: a29Q1000000t6zFIAQ
        xcdio__Start_Date__c:
          type: string
          format: date
          description: Leave start date.
          example: '2025-01-10'
        xcdio__Start_Date_AM_PM_All_Day__c:
          type: string
          enum:
            - AM
            - PM
            - All Day
          description: Leave start slot.
          example: All Day for a full day, or PM if the leave starts from the second half of the day.
        xcdio__End_Date__c:
          type: string
          format: date
          description: Leave end date.
          example: '2025-01-10'
        xcdio__End_Date_AM_PM_All_Day__c:
          type: string
          enum:
            - AM
            - PM
            - All Day
          description: Leave end slot.
          example: All Day for a full day, or AM if the leave is until the first half of the day.
        xcdio__Illness__c:
          type: string
          enum:
            - Back & neck
            - Chest & respiratory
            - Covid-19 confirmed
            - Covid-19 suspected
            - Covid-19 self-isolating
            - Diabetes
            - Eyes, ear, nose, mouth
            - Genito-urinary
            - Heart
            - Infection
            - Musculo-skeletal
            - Neurological
            - Pregnancy
            - Stomach
            - Stress
            - Other
          description: Applicable for sickness only. The enum values may vary depending on client customizations.
          example: Other
        xcdio__Expected_return_to_work_date__c:
          type: string
          format: date
          description: Expected reurn to work date. Applicable for sickness only.
          example: '2025-01-10'
        xcdio__Industrial_injury__c:
          type: string
          format: boolean
          description: Industrial Injury. Applicable for sickness only.
          example: false
        xcdio__Notes__c:
          type: string
          description: Leave Notes.
          
    BookLeaveApiResponseSuccess:
      type: object
      properties:
        success:
          type: boolean
          example: "true"
          description: The status of the leave request record in the request array.
        errors:
          type: array
          items:
            type: string
          example:  []
        xcdio__Leave_Request__c:
          type: string
          example: a10Q100000kS97VIAS
          description: Salesforce record ID of the leave request.
        Id:
          type: string
          example: a29Q1000000t6zFIAQ
          description: Salesforce record ID of the API object record.
        record_Sequence:
          type: integer
          description: Sequence number of the record provided in the request array.
          example: 1
          
    BookLeaveAsyncApiResponseSuccess:
      type: object
      properties:
        batch_id:
          type: string
          example: "1ea4b976fa600903"
          description: The status of the leave request record in the request array.
        errors:
          type: array
          items:
            type: string
          example:  []
          
    BookLeaveApiResponseFailure:
      type: object
      properties:
        success:
          type: boolean
          description: The status of the leave request record in the request array.
          example: "true"
        errors:
          type: array
          items:
            type: string
          example:  []
          
    EditLeave:
      type: object
      required:
        - records
      properties:
        records:
          type: array
          description: Array of leave request records to be edited, as described in the EditLeaveRecordDetail schema. Every XCD API has a threshold number of records that can be passed in a single synchronous request, defined in the "XCD Integration API" custom metadata. The number of records in an asynchronous request can be up to 10,000.
          items:
            $ref: '#/components/schemas/EditLeaveRecordDetail' 
        asynchronous:
          type: string
          description: Request execution context. Synchronous requests will provide a response as part of the same request. Asynchronous requests return a single batch_Id for the entire array, which can be further queried for the request status and other fields. Refer GraphQL API section in this document on how to query request details using batch_id. 
          format: boolean
          default: "false"
        allOrNone:
          type: string
          format: boolean
          default: true
          description: Allow partial leave records to be created if one or more records in the array have validation errors.
    
    EditLeaveRecordDetail:
      type: object
      properties:
        xcdio__Leave_request__c:
          type: string
          description: Salesforce record ID of the leave request to be edited or canceled.
          example: a10Q100000iqtztIAA
        xcdio__Approval_Status__c:
          type: string
          example: Cancelled
servers:
  - url: https://mydomain.my.salesforce.com/services/{URI}
    #description: Server for different paths
    variables:
      URI:
        enum:
          - apexrest/xcdio/xcdapi/v1.0
          - data/v61.0/graphql
        default: apexrest/xcdio/xcdapi/v1.0
        
    
tags:
  - name: Leave 
    description: 'Book, edit, and cancel leave in XCD'
  - name: GraphQL API
    description: 'Query XCD & Other Salesforce Object Records (URI - data/v61.0/graphql)'
